name: parking-manager
services:
  pg:
    image: postgres:15-alpine
    ports:
    - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=parkingmanager
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: