spring:
  application:
    name: parkingmanager
  datasource:
    url: jdbc:postgresql://localhost:5432/parkingmanager
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: filesystem:db/migration
    baseline-on-migrate: true
  logging:
    level:
      org:
        springframework:
          autoconfigure: warn